name: Bump dev version of Python package
description: Bump Python package to a guessed development version
# NOTE: Needs GITHUB_TOKEN env variable

inputs:
  init-file:
    description: Path to __init__.py
    required: true

runs:
  using: composite
  steps:
    - name: Install utils
      shell: bash
      run: python3 -m pip install packaging

    - name: Install module
      shell: bash
      run: python3 -m pip install -e .

    - name: Configure git
      shell: bash
      run: ${{ github.action_path }}/../../configure-git/configure-git.sh

    - name: Set env vars
      shell: bash
      run: |
        echo "INIT_FILE=${{ inputs.init-file }}" >> "$GITHUB_ENV"
        echo "REVIEWER=${{ github.event.pull_request.merged_by.login }}" >> "$GITHUB_ENV"

    - name: Guess new dev version
      id: guess
      shell: python
      run: |
        import os
        import importlib.util
        from packaging.version import Version

        # Dynamically import __init__.py
        spec = importlib.util.spec_from_file_location('tmp_module', os.environ['INIT_FILE'])
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        # Get version
        ver = Version(module.__version__)

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          print(f'new-micro={ver.major}.{ver.minor}.{ver.micro + 1}.dev', file=f)

          if str(ver) == ver.base_version and ver.micro == 0:
            print(f'bugfix-branch={ver.major}.{ver.minor}.x', file=f)
            print(f'new-minor={ver.major}.{ver.minor + 1}.0.dev', file=f)

    - name: Create new micro/bugfix branch if needed
      if: ${{ steps.guess.outputs.bugfix-branch }}
      id: bugfix-branch
      shell: bash
      env:
        PS4: '[command]'
        BRANCH: ${{ steps.guess.outputs.bugfix-branch }}
      run: |
        set -x
        git branch "$BRANCH"
        git push origin "$BRANCH"

    - name: Create PR for micro/bugfix bump
      shell: bash
      env:
        BASE_BRANCH: ${{ steps.guess.outputs.bugfix-branch || github.event.pull_request.base.ref }}
        VERSION: ${{ steps.guess.outputs.new-micro }}
      run: ${{ github.action_path }}/create-pr.sh

    - name: Create PR for minor bump
      if: ${{ steps.guess.outputs.new-minor }}
      shell: bash
      env:
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        VERSION: ${{ steps.guess.outputs.new-minor }}
      run: ${{ github.action_path }}/create-pr.sh
